global:
  resolve_timeout: 15s

route:
  receiver: 'default'
  group_wait: 10s
  group_interval: 15s
  routes:
    - match:
        node: 'HighCPU'
      receiver: 'HighCPU'
    - match:
        node: 'NodeDown'
      receiver: 'NodeDown'

receivers:
  - name: 'default'
    slack_configs:
      - channel: "#default"
        send_resolved: true
        api_url: 'https://hooks.slack.com/services/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'

  - name: 'HighCPU'
    slack_configs:
      - channel: "#highcpu-app"
        send_resolved: true
        api_url: 'https://hooks.slack.com/services/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'
  
  - name: 'NodeDown'
    slack_configs:
      - channel: "#nodedown-app"
        send_resolved: true
        api_url: 'https://hooks.slack.com/services/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'
    email_configs:
      - to: moamenahmed800@gmail.com
        from: moamenahmed800@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: moamenahmed800@gmail.com
        auth_identity: moamenahmed800@gmail.com
        auth_password: wzsj rlst vtsf ggse
        send_resolved: true
  